---

- hosts: all
  remote_user: root
  become: yes
  become_method: sudo
  vars:
    deploy_user: deploy
    ruby_v: 2.3.1
    rbenv_ruby_initial: 'global'

  tasks:
  - name: update cache
    apt: update_cache=yes

  - name: install additional libs
    apt: name={{ item }} state=present
    with_items:
      - git
      - htop
      - nodejs
      - build-essential
      - libssl-dev
      - libyaml-dev
      - libreadline6-dev
      - zlib1g-dev
      - libcurl4-openssl-dev
      - build-essential
      - postgresql
      - postgresql-contrib
      - libpq-dev
      - python-psycopg2
      - git-core
      - curl
      - nginx
      - redis-server
      - imagemagick
      - libmagickcore-dev
      - libmagickwand-dev

  - name: Ensure the PostgreSQL service is running
    service: name=postgresql state=started enabled=yes

  - name: Create user
    user:
      name: '{{ deploy_user }}'

  - name: Install RbEnv
    become_user: '{{ deploy_user }}'
    git:
      repo: https://github.com/sstephenson/rbenv.git
      dest: ~/.rbenv

  - name: Add bash_profile
    become_user: '{{ deploy_user }}'
    command: touch $HOME/.bash_profile
    args:
      creates: $HOME/.bash_profile

  - name: Add new path to bash_profile $PATH
    become_user: '{{ deploy_user }}'
    lineinfile:
      dest: .bash_profile
      line: 'export PATH="$HOME/.rbenv/bin:$PATH"'
      state: present

  - name: Auto initial RbENV when log in to shell
    become_user: '{{ deploy_user }}'
    lineinfile:
      dest: .bash_profile
      line: 'eval "$(rbenv init -)"'
      state: present

  - name: Installing ruby-build plugin
    become_user: '{{ deploy_user }}'
    git:
      repo: https://github.com/sstephenson/ruby-build.git
      dest: ~/.rbenv/plugins/ruby-build

  - name: Installing rbenv-gem-rehash plugin
    become_user: '{{ deploy_user }}'
    git:
      repo: https://github.com/sstephenson/rbenv-gem-rehash.git
      dest: ~/.rbenv/plugins/rbenv-gem-rehash

  - name: Installing Ruby
    become_user: '{{ deploy_user }}'
    shell: 'source $HOME/.bash_profile && rbenv install {{ ruby_v }} -s'
    args:
      executable: /bin/bash

  - name: Initial Ruby (at home directory)
    become_user: '{{ deploy_user }}'
    shell: 'source $HOME/.bash_profile && rbenv {{ rbenv_ruby_initial }} {{ ruby_v }}'
    args:
      executable: /bin/bash

  - name: Install bundler
    become_user: '{{ deploy_user }}'
    shell: 'source $HOME/.bash_profile && gem install bundler --no-ri --no-rdoc'
    args:
      executable: /bin/bash
